### ISSUE TITLE
イシューをコミットメッセージに紐づけて閉じる方法を理解して使う

### ISSUE THREAD

**Issue by norotime** [KaoruOnuki/Followup_assignment#13]
https://help.github.com/articles/closing-issues-using-keywords/

**Comment by norotime** [comment]
@KaoruOnuki ぜひ、こちらの方法を今後は活用してください。現場でもよくやっています。
また、イシューは完了したら手動でも良いので閉じましょう！

**Comment by KaoruOnuki** [comment]
@norotime さん、おお！すごいですね！ありがとうございます。読みました。今後気をつけます。
