### ISSUE TITLE
クラス図（Class Diagram） を作成しましょう

### ISSUE THREAD

**Issue by norotime** [KaoruOnuki/Followup_assignment#9]
参考：P.12
http://www.ssu.ac.jp/home/h-taka/seminar2012/uml.pdf

https://www.ogis-ri.co.jp/otc/swec/process/am-res/am/artifacts/classDiagram.html

http://www.itmedia.co.jp/im/articles/0407/16/news081.html

**Comment by KaoruOnuki** [comment]
[group_rps.pdf](https://github.com/KaoruOnuki/group_rps/files/2130545/group_rps.pdf)

**Comment by norotime** [comment]
@KaoruOnuki GameとJudgementの2つにしたのですね！
